{% set name = "wwt_data_formats" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wwt_data_formats-{{ version }}.tar.gz
  sha256: f7afa309116a1de869f1abf5834108c839a813bf21327f7c53b8832c8ed70164

build:
  number: 0
  noarch: python
  entry_points:
    - wwtdatatool=wwt_data_formats.cli:entrypoint
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - requests
    - traitlets

test:
  imports:
    - wwt_data_formats
    - wwt_data_formats.tests
  commands:
    - pip check
    - wwtdatatool --help
    - pytest --pyargs wwt_data_formats
  requires:
    - beautifulsoup4
    - mock
    - numpy
    - pip
    - pytest
    - pytest-mock

about:
  home: https://wwt-data-formats.readthedocs.io/
  summary: Low-level interface to AAS WorldWide Telescope data formats
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pkgw
